name: CI-CD
on:
  push:
    branches: ["main"]    
  workflow_dispatch: 
  #Permite disparar manualmente a pipeline
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:

    - name: Docker Login
      uses: docker/login-action@v3.0.0      
      # Opção para fazer login diretamente
      # with:      
      #   registry: repositorio
      #   username: usuario
      #   password: senha
      
      # Opção utlizando secrets do github
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    
    - name: Baixar o repositorio
      run: echo "Baixando repositorio"
      
    - name: Criar image do container
      run: echo "Criando image"

    - name: Push na image
      run: echo "Enviando image para o repositorio"

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Fazendo o deploy
      run: echo "Fazendo o deploy"    
    
