name: CI-CD
on:
  push:
    branches: ["main"]    
  workflow_dispatch: 
  #Permite disparar manualmente a pipeline
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar o repositorio
      run: echo "Baixando repositorio"
      
    - name: Criar image do container
      run: echo "Criando image"

    - name: Push na image
      run: echo "Enviando image para o repositorio"

  CD:
    runs-on: ubuntu-latest
    steps:
    - name: Fazendo o deploy
      run: echo "Fazendo o deploy"    
    
